baseURL: "https://grubd14.github.io/"
title: Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: g14
    description: "Blog Site for what i Learned"
    keywords: [Blog, Portfolio, PaperMod]
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: false
    hideFooter: true


    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: '/favicon.ico'
        favicon16x16: '/favicon-16x16.png'
        favicon32x32: '/favicon-32x32.png'
        apple_touch_icon: '/apple-touch-icon.png'
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "grubd14"
        icon: '/home.svg'
        iconHeight: 40

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Blog
        subtitle: "Welcome to my blog"
        imageUrl: '/logo.png'
        imageWidth: 300
        imageHeight: 300
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags
    markup:
        highlight:
             style: monokai
             codeFences: true
    # home-info mode
    # homeInfoParams:
    #     Title: "Hi there \U0001F44B"
    #     Content: Welcome to my blog

    socialIcons:
        - name: github
          url: "https://github.com/grubd14"
        - name: reddit
          url: "https://reddit.com/"
        - name: facebook
          url: "https://facebook.com/"
        - name: twitter
          url: "https://twitter.com"



    cover:
        responsiveImages: true

    # # for search
    # https://fusejs.io/api/options.html
    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        # - identifier: search
        #   name: search
        #   url: /search/
        #   weight: 20
        - identifier: website
          name: Github
          url: https://github.com/grubd14/grubd14.github.io
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai


